apiVersion: v1
kind: ConfigMap
metadata:
  name: mopidy-config
data:
  mopidy-input.yaml: |
    http:
      hostname: 0.0.0.0
    musicbox_webclient:
      enabled: true
      musicbox: false
      on_track_click: PLAY_ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopidy
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mopidy
      app.kubernetes.io/name: mopidy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mopidy
        app.kubernetes.io/instance: mopidy
    spec:
      containers:
      - name: mopidy
        image: ghcr.io/tyz/mopidy-docker:3.4.2
        imagePullPolicy: IfNotPresent

        securityContext:
          # Access to hardware devices
          privileged: true

        volumeMounts:
        # Access to the ALSA devices
        - mountPath: /dev/snd
          name: alsa
          readOnly: false
          # Host's ALSA config
        - mountPath: /etc/asound.conf
          name: asound-conf
          readOnly: true
        - mountPath: /tmp/config
          name: config-volume
          readOnly: true

      # For ALSA dmix
      hostIPC: true

      # Required for zeroconf
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      securityContext:
        # The 'audio' group, to access /dev/snd/*
        supplementalGroups:
        - 29

      volumes:
      - hostPath:
          path: /dev/snd
        name: alsa
      - hostPath:
          path: /etc/asound.conf
          type: File
        name: asound-conf
      - configMap:
          name: mopidy-config
        name: config-volume
